CREATE TABLE PACIENTE (
    NOME_PACIENTE VARCHAR2(255),
    IDADE NUMBER,
    SEXO VARCHAR2(1 CHAR),
    RUA VARCHAR2(255),
    CEP NUMBER,
    BAIRRO VARCHAR2(255),
    CIDADE VARCHAR2(255),
    ESTADO VARCHAR2(2 CHAR),
    ID_PACIENTE NUMBER,
    CODIGO_USUARIO NUMBER,
    NOME_CARTAO VARCHAR2(255),
    DATA_NASCIMENTO DATE,
    NOME_MAE VARCHAR2(255),
    RG NUMBER,
    DATA_EXPEDICAO_RG DATE,
    CPF NUMBER,
    NUMERO_CNS NUMBER,
    TELEFONE NUMBER,
    CNPJ NUMBER,
    IE NUMBER,
    PACIENTE_TIPO NUMBER,
    CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PACIENTE, CODIGO_USUARIO)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA NUMBER,
    ID_PACIENTE NUMBER,
    DATA_SOLICITACAO DATE,
    FK_PACIENTE_ID_PACIENTE NUMBER,
    FK_PACIENTE_CODIGO_USUARIO NUMBER,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_CONSULTA, ID_PACIENTE)
);

CREATE TABLE TRIAGEM (
    ID_TRIAGEM NUMBER,
    TIPO_TRIAGEM VARCHAR2(255),
    FK_MEDICO_COD_MEDICO NUMBER,
    CONSTRAINT PK_TRIAGEM PRIMARY KEY (ID_TRIAGEM)
);

CREATE TABLE MEDICO (
    COD_MEDICO NUMBER,
    NOME_MEDICO VARCHAR2(255),
    CEP NUMBER,
    RUA VARCHAR2(255),
    BAIRRO VARCHAR2(255),
    CIDADE VARCHAR2(255),
    ESTADO VARCHAR2(2 CHAR),
    TELEFONE NUMBER,
    CONSTRAINT PK_MEDICO PRIMARY KEY (COD_MEDICO)
);

CREATE TABLE MEDICAMENTO (
    COD_MEDICAMENTO NUMBER,
    NOME VARCHAR2(255),
    POSOLOGIA VARCHAR2(255),
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (COD_MEDICAMENTO)
);

CREATE TABLE INSTRUMENTOS (
    COD_INSTRUMENTO NUMBER,
    NOME VARCHAR2(255),
    TIPO VARCHAR2(255),
    CONSTRAINT PK_INSTRUMENTOS PRIMARY KEY (COD_INSTRUMENTO)
);

CREATE TABLE TEM (
    FK_CONSULTA_ID_CONSULTA NUMBER,
    FK_CONSULTA_ID_PACIENTE NUMBER,
    FK_TRIAGEM_ID_TRIAGEM NUMBER,
    CONSTRAINT PK_TEM PRIMARY KEY (FK_CONSULTA_ID_CONSULTA, FK_CONSULTA_ID_PACIENTE, FK_TRIAGEM_ID_TRIAGEM)
);

CREATE TABLE RECEITA (
    FK_MEDICO_COD_MEDICO NUMBER,
    FK_MEDICAMENTO_COD_MEDICAMENTO NUMBER,
    CONSTRAINT PK_RECEITA PRIMARY KEY (FK_MEDICO_COD_MEDICO, FK_MEDICAMENTO_COD_MEDICAMENTO)
);

CREATE TABLE POSSUI (
    FK_MEDICO_COD_MEDICO NUMBER,
    FK_INSTRUMENTOS_COD_INSTRUMENTO NUMBER,
    CONSTRAINT PK_POSSUI PRIMARY KEY (FK_MEDICO_COD_MEDICO, FK_INSTRUMENTOS_COD_INSTRUMENTO)
);

CREATE TABLE EXAMINA (
    FK_MEDICO_COD_MEDICO NUMBER,
    FK_PACIENTE_ID_PACIENTE NUMBER,
    FK_PACIENTE_CODIGO_USUARIO NUMBER,
    DATA_CONSULTA DATE,
    HORARIO_CONSULTA DATE,
    CONSTRAINT PK_EXAMINA PRIMARY KEY (FK_MEDICO_COD_MEDICO, FK_PACIENTE_ID_PACIENTE, FK_PACIENTE_CODIGO_USUARIO)
);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_2
    FOREIGN KEY (FK_PACIENTE_ID_PACIENTE, FK_PACIENTE_CODIGO_USUARIO)
    REFERENCES PACIENTE (ID_PACIENTE, CODIGO_USUARIO)
    ON DELETE CASCADE;

ALTER TABLE TRIAGEM ADD CONSTRAINT FK_TRIAGEM_2
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE RESTRICT;

ALTER TABLE TEM ADD CONSTRAINT FK_TEM_1
    FOREIGN KEY (FK_CONSULTA_ID_CONSULTA, FK_CONSULTA_ID_PACIENTE)
    REFERENCES CONSULTA (ID_CONSULTA, ID_PACIENTE)
    ON DELETE RESTRICT;

ALTER TABLE TEM ADD CONSTRAINT FK_TEM_2
    FOREIGN KEY (FK_TRIAGEM_ID_TRIAGEM)
    REFERENCES TRIAGEM (ID_TRIAGEM)
    ON DELETE RESTRICT;

ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE SET NULL;

ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_2
    FOREIGN KEY (FK_MEDICAMENTO_COD_MEDICAMENTO)
    REFERENCES MEDICAMENTO (COD_MEDICAMENTO)
    ON DELETE SET NULL;

ALTER TABLE POSSUI ADD CONSTRAINT FK_POSSUI_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE SET NULL;

ALTER TABLE POSSUI ADD CONSTRAINT FK_POSSUI_2
    FOREIGN KEY (FK_INSTRUMENTOS_COD_INSTRUMENTO)
    REFERENCES INSTRUMENTOS (COD_INSTRUMENTO)
    ON DELETE SET NULL;

ALTER TABLE EXAMINA ADD CONSTRAINT FK_EXAMINA_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE RESTRICT;

ALTER TABLE EXAMINA ADD CONSTRAINT FK_EXAMINA_2
    FOREIGN KEY (FK_PACIENTE_ID_PACIENTE, FK_PACIENTE_CODIGO_USUARIO)
    REFERENCES PACIENTE (ID_PACIENTE, CODIGO_USUARIO)
    ON DELETE RESTRICT;
	
CREATE OR REPLACE TRIGGER INSERECONSULTAAFTERINSERT
AFTER INSERT ON CONSULTA
FOR EACH ROW
DECLARE
    mensagem VARCHAR2(100);
BEGIN
    mensagem := 'Consulta inserida para o paciente de ID ' || :NEW.ID_PACIENTE || 
                ' na data ' || TO_CHAR(:NEW.DATA_SOLICITACAO, 'DD-MM-YYYY HH24:MI:SS');
    DBMS_OUTPUT.PUT_LINE('Mensagem: ' || mensagem);
END;

INSERT INTO CONSULTA (ID_CONSULTA, ID_PACIENTE, DATA_SOLICITACAO)
VALUES (1, 1, TO_DATE('23-09-2023', 'DD-MM-YYYY'));

--

CREATE OR REPLACE FUNCTION OBTERDETALHESPACIENTE(
    id_paciente IN INT
) RETURN VARCHAR2
IS
    nome_paciente VARCHAR2(100);
    idade INT;
BEGIN
    SELECT NOME_PACIENTE, IDADE
    INTO nome_paciente, idade
    FROM PACIENTE
    WHERE ID_PACIENTE = id_paciente;

    RETURN 'Nome do Paciente: ' || nome_paciente || ', Idade: ' || idade;
END;

SELECT OBTERDETALHESPACIENTE(1) FROM DUAL;