CREATE DATABASE UBS_DIGITAL;
USE UBS_DIGITAL;

CREATE TABLE PACIENTE (
    NOME_PACIENTE CHARACTER,
    IDADE INT,
    SEXO CHARACTER,
    RUA CHARACTER,
    CEP INT,
    BAIRRO CHARACTER,
    CIDADE CHARACTER,
    ESTADO CHARACTER,
    ID_PACIENTE INT,
    CODIGO_USUARIO INT,
    NOME_CARTAO CHARACTER,
    DATA_NASCIMENTO DATE,
    NOME_MAE CHARACTER,
    RG INT,
    DATA_EXPEDICAO_RG DATE,
    CPF INT,
    NUMERO_CNS INT,
    TELEFONE INT,
    CNPJ INT,
    IE INT,
    PACIENTE_TIPO INT,
    PRIMARY KEY (ID_PACIENTE, CODIGO_USUARIO)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA INT,
    ID_PACIENTE INT,
    DATA_SOLICITACAO DATE,
    FK_PACIENTE_ID_PACIENTE INT,
    FK_PACIENTE_CODIGO_USUARIO INT,
    PRIMARY KEY (ID_CONSULTA, ID_PACIENTE)
);

CREATE TABLE TRIAGEM (
    ID_TRIAGEM INT PRIMARY KEY,
    TIPO_TRIAGEM CHARACTER,
    FK_MEDICO_COD_MEDICO INT
);

CREATE TABLE MEDICO (
    COD_MEDICO INT PRIMARY KEY,
    NOME_MEDICO CHARACTER,
    CEP INT,
    RUA CHARACTER,
    BAIRRO CHARACTER,
    CIDADE CHARACTER,
    ESTADO CHARACTER,
    TELEFONE INT
);

CREATE TABLE MEDICAMENTO (
    COD_MEDICAMENTO INT PRIMARY KEY,
    NOME CHARACTER,
    POSOLOGIA CHARACTER
);

CREATE TABLE INSTRUMENTOS (
    COD_INSTRUMENTO INT PRIMARY KEY,
    NOME CHARACTER,
    TIPO CHARACTER
);

CREATE TABLE TEM (
    FK_CONSULTA_ID_CONSULTA INT,
    FK_CONSULTA_ID_PACIENTE INT,
    FK_TRIAGEM_ID_TRIAGEM INT
);

CREATE TABLE RECEITA (
    FK_MEDICO_COD_MEDICO INT,
    FK_MEDICAMENTO_COD_MEDICAMENTO INT
);

CREATE TABLE POSSUI (
    FK_MEDICO_COD_MEDICO INT,
    FK_INSTRUMENTOS_COD_INSTRUMENTO INT
);

CREATE TABLE EXAMINA (
    FK_MEDICO_COD_MEDICO INT,
    FK_PACIENTE_ID_PACIENTE INT,
    FK_PACIENTE_CODIGO_USUARIO INT,
    DATA_CONSULTA DATE,
    HORARIO_CONSULTA DATE
);
 
ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_2
    FOREIGN KEY (FK_PACIENTE_ID_PACIENTE, FK_PACIENTE_CODIGO_USUARIO)
    REFERENCES PACIENTE (ID_PACIENTE, CODIGO_USUARIO)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGEM ADD CONSTRAINT FK_TRIAGEM_2
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE RESTRICT;
 
ALTER TABLE TEM ADD CONSTRAINT FK_TEM_1
    FOREIGN KEY (FK_CONSULTA_ID_CONSULTA, FK_CONSULTA_ID_PACIENTE)
    REFERENCES CONSULTA (ID_CONSULTA, ID_PACIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE TEM ADD CONSTRAINT FK_TEM_2
    FOREIGN KEY (FK_TRIAGEM_ID_TRIAGEM)
    REFERENCES TRIAGEM (ID_TRIAGEM)
    ON DELETE RESTRICT;
 
ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE SET NULL;
 
ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_2
    FOREIGN KEY (FK_MEDICAMENTO_COD_MEDICAMENTO)
    REFERENCES MEDICAMENTO (COD_MEDICAMENTO)
    ON DELETE SET NULL;
 
ALTER TABLE POSSUI ADD CONSTRAINT FK_POSSUI_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE SET NULL;
 
ALTER TABLE POSSUI ADD CONSTRAINT FK_POSSUI_2
    FOREIGN KEY (FK_INSTRUMENTOS_COD_INSTRUMENTO)
    REFERENCES INSTRUMENTOS (COD_INSTRUMENTO)
    ON DELETE SET NULL;
 
ALTER TABLE EXAMINA ADD CONSTRAINT FK_EXAMINA_1
    FOREIGN KEY (FK_MEDICO_COD_MEDICO)
    REFERENCES MEDICO (COD_MEDICO)
    ON DELETE RESTRICT;
 
ALTER TABLE EXAMINA ADD CONSTRAINT FK_EXAMINA_2
    FOREIGN KEY (FK_PACIENTE_ID_PACIENTE, FK_PACIENTE_CODIGO_USUARIO)
    REFERENCES PACIENTE (ID_PACIENTE, CODIGO_USUARIO)
    ON DELETE RESTRICT;
    
    