CREATE OR REPLACE TRIGGER INSERECONSULTAAFTERINSERT
AFTER INSERT ON CONSULTA
FOR EACH ROW
DECLARE
    mensagem VARCHAR2(100);
BEGIN
    mensagem := 'Consulta inserida para o paciente de ID ' || :NEW.ID_PACIENTE || 
                ' na data ' || TO_CHAR(:NEW.DATA_SOLICITACAO, 'DD-MM-YYYY HH24:MI:SS');
    DBMS_OUTPUT.PUT_LINE('Mensagem: ' || mensagem);
END;

-- Exemplo:
--INSERT INTO CONSULTA (ID_CONSULTA, ID_PACIENTE, DATA_SOLICITACAO)
--VALUES (1, 1, TO_DATE('23-09-2023', 'DD-MM-YYYY'));